service: go-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-west-2
  environment:
    DB_NAME: "newDB"
    COLLECTION_NAME: "vehicles"
    DOCUMENT_LIMIT: '100'

package:
  patterns:
    - '!./**'
    - ./bin/**

custom:
  serverlessSsmFetch:
    CONNECTION_STRING: /lambda_test/connection_string~true

functions:
  healthcheck:
    handler: bin/healthcheck
    events:
      - httpApi:
          path: /healthcheck
          method: get
  vehicles:
    handler: bin/vehicles
    ssmToEnvironment:
      - CONNECTION_STRING
    events:
      - httpApi:
          path: /vehicles
          method: get

plugins:
  - serverless-ssm-fetch
  - serverless-python-requirements
